title: "| Sustainability and Building Resilience |" 
author: "Amad Kayani"
description: "A.Kayani, 2023"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "CV.md", title: | CV |}
  - {file: "publications.md", title: | Publications |}
  
  - {file: "talks.md", title: | Talks |}
  - {file: "portfolio.md", title: | Portfolio |}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:amad.kayani@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/amadkayani "}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
